/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hospital;

import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.*;
import javax.swing.*;

/**
 *
 * @author anjet
 */
public class Dashboard extends javax.swing.JFrame {
    
    Connection con = null;
    Statement st = null;
    ResultSet rs = null;

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        new_patient_btn = new javax.swing.JButton();
        new_employee_btn = new javax.swing.JButton();
        patient_count_lbl = new javax.swing.JLabel();
        admit_patient_btn = new javax.swing.JButton();
        patients_btn = new javax.swing.JButton();
        employees_btn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Dashboard");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("Dashboard");

        new_patient_btn.setText("New Patient");
        new_patient_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                new_patient_btnActionPerformed(evt);
            }
        });

        new_employee_btn.setText("New Employee");
        new_employee_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                new_employee_btnActionPerformed(evt);
            }
        });

        patient_count_lbl.setText("0");

        admit_patient_btn.setText("Admit Patient");
        admit_patient_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admit_patient_btnActionPerformed(evt);
            }
        });

        patients_btn.setText("View Patients");
        patients_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patients_btnActionPerformed(evt);
            }
        });

        employees_btn.setText("View Employees");
        employees_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employees_btnActionPerformed(evt);
            }
        });

        jLabel2.setText("No. of Patients");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(new_employee_btn)
                            .addComponent(employees_btn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(new_patient_btn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(admit_patient_btn)
                                .addGap(20, 20, 20))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(patients_btn)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(patient_count_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(83, 83, 83))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(new_patient_btn)
                    .addComponent(admit_patient_btn)
                    .addComponent(new_employee_btn))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(patients_btn)
                    .addComponent(employees_btn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(patient_count_lbl)
                    .addComponent(jLabel2))
                .addContainerGap(159, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        try{
            con  = MySqlConnect.ConnectDB();
            String sql = "SELECT count(id) FROM patient";
            st = con.createStatement();
            rs = st.executeQuery(sql);
            int patient_count = 0;
            
            if(rs.next()){
                patient_count = rs.getInt(1);
            }
            patient_count_lbl.setText(Integer.toString(patient_count));
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        
    }//GEN-LAST:event_formWindowOpened

    private void new_employee_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_new_employee_btnActionPerformed
        // TODO add your handling code here:
        close();
        AddEmployee aEmp = new AddEmployee();
        aEmp.setVisible(true);     
    }//GEN-LAST:event_new_employee_btnActionPerformed

    private void employees_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employees_btnActionPerformed
        // TODO add your handling code here:
        close();
        ViewEmployees ve = new ViewEmployees();
        ve.setVisible(true);
    }//GEN-LAST:event_employees_btnActionPerformed

    private void new_patient_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_new_patient_btnActionPerformed
        // TODO add your handling code here:
         close();
        AddPatient pa = new AddPatient();
        pa.setVisible(true);
    }//GEN-LAST:event_new_patient_btnActionPerformed

    private void admit_patient_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admit_patient_btnActionPerformed
        // TODO add your handling code here:
        
        close();
        AddPatientId pa = new AddPatientId();
        pa.setVisible(true);
        
        
    }//GEN-LAST:event_admit_patient_btnActionPerformed

    private void patients_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patients_btnActionPerformed
        // TODO add your handling code here:
        close();
        ViewPatient vp = new ViewPatient();
        vp.setVisible(true);
    }//GEN-LAST:event_patients_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton admit_patient_btn;
    private javax.swing.JButton employees_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton new_employee_btn;
    private javax.swing.JButton new_patient_btn;
    private javax.swing.JLabel patient_count_lbl;
    private javax.swing.JButton patients_btn;
    // End of variables declaration//GEN-END:variables

    public void close(){
        WindowEvent winClosing = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosing);
    }

}
